#!/usr/bin/env bash

# Installing Nginx and configuring it
sudo apt update -y
sudo apt install nginx -y

new_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$HOSTNAME;
}
"

sudo chown "$USER":"$USER" /etc/nginx/sites-available/default
echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo systemctl restart nginx

